### ISSUE TITLE
Drag actions do not reset.

### ISSUE THREAD

**Issue by eranmiller** [PuruVJ/svelte-drag#18]
I'm trying to create a draggable button that returns to original position on "dragend".
The first drag action in either direction works as expected.
However, subsequent drag actions result in the following unexpected behaviors:

I've created this REPL to illustrate the problem:
https://svelte.dev/repl/b981d02745a14df0bd95ba7b41746803?version=3.44.1

Draggable distance increases with each drag... 
Draggable escapes "bounds" element.
DevTools Error (starts to happen after two swipe gestures): [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive.

Please help explain if/how my implementation is at fault. 
Thank you in advance for your help and consideration.

**Comment by PuruVJ** [comment]
Hi, this issue is same as #13. The solution is here https://github.com/PuruVJ/svelte-drag/issues/6#issuecomment-965002472

If you go to the REPL there, you will see the example where you are explicitly controlling the dragging with your own state.

It's in beta right now, but I plan to release it fully in a day or two 🙂

**Comment by eranmiller** [comment]
Thank you!
I've updated the code in my example and confirm all except one of the unexpected behaviors have been addressed.
https://svelte.dev/repl/b981d02745a14df0bd95ba7b41746803?version=3.44.1

DevTools Error (starts to happen after two swipe gestures): [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive.
Results in undesired page scrolling when draggable is moved.

**Comment by PuruVJ** [comment]
Hi, the issue is that yur modifing the `.style` of element directly. I apply `touch-action: none` to make dragging on touch seamless. If you override all of `.style` it won't work. hence, you should do `.style.transform = `

Although, with controlled behavior, you don't need to change transform manually. You can just wait for `on:svelte-drag:end` event and set the x and y state variables to 0 and 0, and it will work, and will be idiomatic with the internal state of draggable too

**Comment by eranmiller** [comment]
Thank you for the clarification!
I removed that incriminating style line and it works as expected.
